import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import logo from "../assets/images/leaves_and_shadows.png";
import Link from "next/link";
import Cookies from 'js-cookie';
import { cinzel } from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Leaves & Shadows",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/leaves_and_shadows.ico" />
      </head>
      <body className="w-screen h-screen bg-zinc-950 flex flex-col items-center overflow-hidden">
    
        {children}
        </body>
    </html>
  );
}
